apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: airbyte-getsales
  description: Airbyte instance for getsales.nl
  links:
    - url: https://airbyte.getsales.nl
      title: Airbyte Instance
      icon: link
  annotations:
    # Add any relevant annotations here, for example:
    # github.com/project-slug: <GitHub project slug>
    # backstage.io/techdocs-ref: url:<URL to TechDocs>
spec:
  type: service
  lifecycle: production # or another suitable lifecycle
  owner: team-data # or another suitable owner
  system: data-platform # or another suitable system
  # ... other spec properties as needed ...
